### ISSUE TITLE
PlacePicker component

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/universal-components#105]
The end goal is to have something like this on mobile. For web, we might to think of how this could work. 

figma designs: https://www.figma.com/file/NTlh7HaG4KE4vDCBIIwEYe3Z/Place-Picker?node-id=0%3A1

- [ ] Input field should display typed text, as well as Badges of selected destinations (cf. below)
- [ ] Input field should have a **X** button to reset it
- [ ] Create row option component @lukewalczak PR #146 
- [ ] Create row options aggregator
- [ ] PLUS icon should add item to the input field as Badge component (which should be dismissed if pressing on it)
- [ ] State of the component should be controlled/controllable by external context
- [ ] Inquire how `KeyboardAvoidingView` is handled by React Native Web

<img width="320" alt="place-picker-from-typing" src="https://user-images.githubusercontent.com/22741774/49796427-f2501600-fd3c-11e8-9dc4-3de9ec913a17.png">

**Comment by FilipMessa** [comment]
Start working on the first subtask 
- [ ] Input field should display typed text, as well as Badges of selected destinations

**Comment by RobinCsl** [comment]
@FilipMessa I believe this was done in #212, closing.
