### ISSUE TITLE
The PlaceCard component

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/universal-components#118]
<img width="409" alt="screen shot 2018-12-13 at 07 33 22" src="https://user-images.githubusercontent.com/6354326/49920263-e170e300-fea9-11e8-9836-8f503fbcebd2.png">

<img width="404" alt="screen shot 2018-12-13 at 07 42 43" src="https://user-images.githubusercontent.com/6354326/49920515-b6d35a00-feaa-11e8-968a-8cfd5e0f62e4.png">

- [x] image 
- [x] price
- [x] place
- [x] country
- [x] clickable (disabled  optionally)
- [ ] loading state with animation (not necessary in the first implementation)

**Comment by RobinCsl** [comment]
#122 took care of first 5 items
