### ISSUE TITLE
Make Storybook debugging easier on mobile device

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/universal-components#127]
If you run storybook on mobile device, there is a problem with time-consuming reload. When you update the component, you have to reload the page (or use live reload), open navigator and find your changed component. This is very ineffective especially for styling or debugging. 

I think there are following possible solutions:

- Use Hot reload – it doesn't work for now, but it would be probably the cleanest solution.
- Set custom initial screen in Storybook
- Possibility to set order of the components in navigator according to name (right now it's probably according to file loading sequence)

**Comment by RobinCsl** [comment]
I believe to make your pain easier in the meantime, you could use the web server available at localhost:7007 which should make interacting with the emulator much easier.

**Comment by ferrannp** [comment]
I will check into this @jvaclavik and see if I can do something to make our lives easier.

**Comment by ferrannp** [comment]
Ahhh @RobinCsl is right. Probably the best is to use http://localhost:7007. Because then when you refresh, you are still in the same page. It is using urls like:

http://localhost:7007/?selectedKind=Badge&selectedStory=Regular%20Badge&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

So in that case for example, when refreshing I am still in the banner one.

**Comment by jvaclavik** [comment]
Well, I use web storybook a lot, but it's not the same. You still have to check you mobile apps very often. And for example when I want to use chrome debugger for checking the structure on the web it's quite hard because you normally see only 3 elements per screen :) Like here:
<img width="1121" alt="screenshot 2018-12-19 at 12 56 53" src="https://user-images.githubusercontent.com/858321/50219037-31f6ad80-038e-11e9-8462-702820bb845e.png">

**Comment by RobinCsl** [comment]
Well, this is because of how React Native Web renders `react-native` code. Maybe using the React dev tools in the browser would be clearer?

**Comment by RobinCsl** [comment]
Closing this, we cannot do much about it, I'm afraid.
