### ISSUE TITLE
Icon name flow type as enum

### ISSUE THREAD

**Issue by tbergq** [kiwicom/universal-components#128]
Would it be possible to generate the Icon flow-type name based on the icons.json file?

So we could get an error compile time if we select wrong icon name?

**Comment by RobinCsl** [comment]
I imagine this should be possible with some flow magic like `$Keys` or `$Values`.

**Comment by tbergq** [comment]
I tried to do this

```
import IconList from '@kiwicom/universal-components/lib/native/Icon/icons.json';

type Props = {|
  +name: $Keys<typeof IconList>,
|}
```
in mobile repo, however it did not work I could pass keys that were not in icons.json without getting flow error

**Comment by RobinCsl** [comment]
But this seems to work
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzBgEsCwBeMAb1TDAAcYBDbAUwC4wAiRl1rgDS0GrbJx6jBqAL4BudPgCe9VmFEBXALYUwAEgDSrRbgA8SlXChFS+AHzzMOMsSzYAck00c12LToDkvGz+8q7Orh5eAEycGtqU-hhMMKIAJkwATiFAA

So I am not sure what's breaking here.

**Comment by tbergq** [comment]
So it must be the import of .json file that breaks flow there 🤔

**Comment by ferrannp** [comment]
Being trying and have same issue. I'm gonna create a script that generates the flow file for us (based on the JSON). It won't be on Github but it will be in npm.
