### ISSUE TITLE
RadioButton: Enhance bullet

### ISSUE THREAD

**Issue by JoseDuSV** [kiwicom/universal-components#136]
- [x] ~~Extract bullet to separate component to make it reusable for more sophisticated select components~~
- [x] Fix check icon centering caused by icons update

**Comment by RobinCsl** [comment]
@JoseDuSV What's the status here?

**Comment by JoseDuSV** [comment]
@RobinCsl Icon centering was fixed by #167 and after we are able to pass any component as button children there is no need for mentioned bullet separation.
So we can close this issue. Thanks
