### ISSUE TITLE
Create the TimelineFlightDetail Component

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/universal-components#137]
## The TimelineFlightDetail Component 

- [ ] after click on item toggle expansion about the detail information on the flight.

figma designs: https://www.figma.com/file/XD9kQTOJxaqviaxD0g3AhAXS/Booking-Detail?node-id=2%3A488

<img width="483" alt="screen shot 2018-12-18 at 11 41 28" src="https://user-images.githubusercontent.com/6354326/50148882-f4285500-02b9-11e9-95b0-2762e0e82697.png">

<img width="518" alt="screen shot 2018-12-18 at 11 41 41" src="https://user-images.githubusercontent.com/6354326/50148865-eb378380-02b9-11e9-96d9-ea7d50671f0c.png">

**Comment by RobinCsl** [comment]
This is already in Margarita, closing the issue.
