### ISSUE TITLE
Timeline Component

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/universal-components#142]
## Timeline Component
related #137 and #138 (wait until these will be finished)

figma designs: https://www.figma.com/file/XD9kQTOJxaqviaxD0g3AhAXS/Booking-Detail?node-id=0%3A1

**requirements**
- [ ] one way
- [ ] one way with overnight
- [ ] one way complicated

- [ ] return
- [ ] return with overnight
- [ ] return complicated

<img width="282" alt="screen shot 2018-12-19 at 09 35 56" src="https://user-images.githubusercontent.com/6354326/50208457-85a6ce00-0371-11e9-9873-091280bcf9a7.png">

**Comment by ferrannp** [comment]
![screenshot 2018-12-19 at 16 31 04](https://user-images.githubusercontent.com/774577/50229828-7f354800-03ab-11e9-9fa2-afde52404582.png)

This is from `mobile`. Is this the same component but different layout? Should we extract it from `mobile`? @tbergq @RobinCsl

**Comment by RobinCsl** [comment]
I believe it is mostly the same component, in terms of data to be presented. The layout is different indeed. I guess we can try to extract from `mobile` what can be extracted. However, the data layer might be slightly different as well since we implement our own GQL server so the queries might change, etc.

**Comment by RobinCsl** [comment]
Yes, you're right. But I guess, we still need to think about the object structure of the props we want to pass.

**Comment by tbergq** [comment]
This component belongs in margarita repo. We should but only atomic components in this repo.

**Comment by RobinCsl** [comment]
Closing this, this should live in Margarita.
