### ISSUE TITLE
Get rid of post install scripts

### ISSUE THREAD

**Issue by ferrannp** [kiwicom/universal-components#149]
1. [x] For `postInstall.js` which is only patching `intl`, we could just fork the repo
2. [ ] For generate icon types, we can have our own repo with `icons.json` and types there

**Comment by RobinCsl** [comment]
> For generate icon types, we can have our own repo with icons.json and types there

This is documented in https://github.com/kiwicom/universal-components/blob/master/CONTRIBUTING.md#updating-icons, so I am closing this issue.
