### ISSUE TITLE
Restrict Icon style prop NOT to modify fontSize and color

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/universal-components#164]
Follow suggestion from this comment: https://github.com/kiwicom/mobile/pull/1385#discussion_r242075422

**Comment by tbergq** [comment]
Seems that this is not possible, since the real validation here lies within StyleSheet.create
`create(styles: PlatformStyleObjectType): StyleObjectType`

And the type of `StylePropType` really evaluates to `any` so
```
$Rest<
  StylePropType,
  {|
    color: *,
    fontSize: *,
  |}
>;
```
is not really possible
