### ISSUE TITLE
Document our standard for commit messages in CONTRIBUTING.md

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/universal-components#166]
This stems from https://github.com/kiwicom/universal-components/pull/163#issuecomment-450658290 (copied below)

@mrtnzlml said:
>I would highly recommend improving Git messages if they are failing in this job. They are meant for programmers and they should be in a digestible format including reasoning why did something change or what is the reasoning behind it. I cannot imagine a better way of describing the project history.
>The problem I see is that people around us just don't consider commit messages to be important (and then it would make sense to basically duplicate the logs and make them better, yes). Look at for example this repo: it's very hard to find a reasoning "why" this commit or explanation in more details. Maybe somewhere in PRs but that's gone the time you close them. Now compare it with better logs - it's very easy to find there an explanation in the commit description. I think it's really important.
>I would say less of chore/fix/enhance prefixes and more Git message descriptions. :)

This would achieve the goal of providing context/explanations as to why changes were made (instead of recording them only in PR discussions). 
For example, if the discussion in the PR is fruitful/useful for posterity, amend your commit message with a digest of the discussion if it was not complete enough already.

**Comment by RobinCsl** [comment]
That's a good start.

I think we also need to add more descriptive context as to what happens in the PR if the title does not encompass everything; I like this approach on `react-native` repository where they add a `Summary`, in that way the git history becomes way more documenting.
<img width="992" alt="screenshot 2019-01-03 at 13 37 17" src="https://user-images.githubusercontent.com/22741774/50638093-c18a8780-0f5c-11e9-8253-e519a2e80c91.png">

**Comment by lukewalczak** [comment]
Maybe we should create a [pr template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) with fields: `Summary`, `Fixes` and some checklist bullets (something similar to [orbit-components repo](https://github.com/kiwicom/orbit-components/))?

**Comment by RobinCsl** [comment]
I was looking at that earlier, but I am not sure this actually populates the commit message. If it does, then problem solved. If it does not, we'll have to inquire more.

**Comment by lukewalczak** [comment]
Always PR description is added to commit as a "summary". 

For example: [your PR description](https://github.com/kiwicom/universal-components/pull/170) is added [there](https://github.com/kiwicom/universal-components/commit/25819a3583892aab490e29fad8879130613f4798)

**Comment by RobinCsl** [comment]
Well, actually, I added manually this message to my commit message when committing my code. 
I don't think GitHub adds anything to my commit message, it just parsed it and displayed it in the PR description. 
What I would like is something like
```
git commit
```
Editor opens
```
#commit message
Added: My component displaying unicorns
Summary: <Fill me please>
#end commit message
```

**Comment by mrtnzlml** [comment]
I think you have it a bit twisted guys. 😊 I always write commit message and proper description and when I open PR then it's added automatically to PR description (and not vice versa). Works in GitLab, GitHub, everywhere. Point is to have it in the commit message because PRs are not part of the history.

I believe it's better to spend 5 minutes on good commit message and summary and 5 seconds opening PR (not the oposite). :)

**Comment by lukewalczak** [comment]
You're totally right. I think we should follow it as well in that project.

**Comment by RobinCsl** [comment]
@mrtnzlml That's exactly what I was trying to express from the start. 😄
