### ISSUE TITLE
Enhance CheckBox component

### ISSUE THREAD

**Issue by JoseDuSV** [kiwicom/universal-components#187]
- [x] Add accessibility
- [x] ~~`value` + `name` props are currently used only in **web** version, decide if can be beneficial to somehow also use it in **native**~~
- [x] Try to unify current `onPress` -> `onChange` implementation in **native** with **web** version

**Comment by RobinCsl** [comment]
@JoseDuSV Is there any progress on this? Just to make sure the checkboxes stay up to date.

**Comment by JoseDuSV** [comment]
@RobinCsl I just created new #218 PR which should close this one. Accessibility and `onChange` handling was updated. 
And so far there was no reason to somehow use `value` or `name` in **native** version. So we should keep it as it is.
