### ISSUE TITLE
Enable icons in Docz

### ISSUE THREAD

**Issue by JoseDuSV** [kiwicom/universal-components#202]
Enable `orbit-icons` font loading in Docz required by `Icon` component.

Adding font like `Roboto` should be quite easy by extending `htmlContext` and `themeConfig` section in `doczrc.js`.
But for `orbit-icons` we will probably need to use `modifyBundlerConfig` section.

**Comment by RobinCsl** [comment]
- [ ] Add orbit-icons 
    - [x] on production site (https://github.com/kiwicom/universal-components/pull/206)
    - [ ] on dev server
- [ ] Add Roboto
