### ISSUE TITLE
Add component for BadgeGrid

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/universal-components#216]
We should be able to create badges like those:

<img width="324" alt="screenshot 2019-02-01 at 12 37 45" src="https://user-images.githubusercontent.com/858321/52121007-76789880-261e-11e9-8bc5-4dbc1044f5cc.png">

It also combines logos of the transporter with vehicle icon. Designer should explain it more.

**Comment by JoseDuSV** [comment]
Is it somehow different from `CarrierLogo` component that we already have? https://deploy-preview-211--kiwicom-universal-components.netlify.com/?selectedKind=CarrierLogo&selectedStory=Four%20carriers&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by RobinCsl** [comment]
https://kiwicom-universal-components.netlify.com/?selectedKind=CarrierLogo&selectedStory=Four%20carriers&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by jvaclavik** [comment]
True, sorry. Closing issue
