### ISSUE TITLE
[Refactor] Create the new DatePicker

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/universal-components#260]
link to design: https://www.figma.com/file/FcnMYRbUEsOIgARMQ2jkpiB1/Date-Picker
<img width="1032" alt="screen shot 2019-03-01 at 11 13 08" src="https://user-images.githubusercontent.com/6354326/53631542-0c4e1600-3c13-11e9-9116-4ab2c063de27.png">

**Comment by JoseDuSV** [comment]
We should probably find some new name for this extended implementation. Or maybe call current version something like `SimpleDatePicker`.
Because we still have some use cases where current native implementation will probably be more suitable. For example birth date in passenger form.
