### ISSUE TITLE
Add build scripts

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/universal-components#74]
Resulting build should make components available like:
`import { Button } from '@kiwicom/universal-orbit-components/react-native`
`import { Button } from '@kiwicom/universal-orbit-components/web`

Or maybe it would be better to have
`import { Button } from '@kiwicom/universal-orbit-components`
but we need to make sure that the web-client does not need to load the bundle for both web and RN. 

@tbergq @FilipMessa please, add your requirements, or discuss the above.

**Comment by tbergq** [comment]
Well, I think for the setup of margarita, we don't need this module to be transpiled. 

But other consumers might 🤔
