### ISSUE TITLE
Extract FlightTimeline component

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/universal-components#87]
This relates to this view on FE:
![06-results-detail1](https://user-images.githubusercontent.com/22741774/49294942-a9829c80-f4b4-11e8-83a3-20210f309822.PNG)

And we have this in MMB on [mobile](https://github.com/kiwicom/mobile/blob/master/app/MMB/src/scenes/tripOverview/Timeline.js).
![simulator screen shot - iphone x - 2018-11-30 at 14 13 40](https://user-images.githubusercontent.com/22741774/49294774-2feaae80-f4b4-11e8-9960-87ae5ef487d9.png)

**Comment by JoseDuSV** [comment]
Blocked, waiting for design update.

**Comment by RobinCsl** [comment]
I believe this is not blocked anymore. We can tackle this issue after our first milestone is reached.

**Comment by RobinCsl** [comment]
This should be in `margarita`. Closing this.
