### ISSUE TITLE
Create the StopoverArrow component

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/universal-components#93]
# StopoverArrow

### props
- stops: *number* (default value 0, max 4)

#### Without stopover
<img width="274" alt="screen shot 2018-12-04 at 12 57 37" src="https://user-images.githubusercontent.com/6354326/49440540-3d5dac80-f7c4-11e8-8bc3-8d0bc9186e3b.png">
#### With stopover
<img width="281" alt="screen shot 2018-12-04 at 12 57 31" src="https://user-images.githubusercontent.com/6354326/49440541-3df64300-f7c4-11e8-9874-ca4557d8d705.png">

**Comment by FilipMessa** [comment]
Blocked, because the design will be updated

**Comment by FilipMessa** [comment]
Design updated, ready to development

**Comment by jvaclavik** [comment]
We can probably decline this issue, because this component will not be in new design.
